import {build} from 'esbuild';import {mkdir,readFile,writeFile,readdir} from 'node:fs/promises';
const manifest=JSON.parse(await readFile('retro-museum.json','utf8'));
const randomPlugin={name:'isolated-random',setup(b){b.onResolve({filter:/^node:crypto$/},()=>({path:'random',namespace:'isolated'}));b.onLoad({filter:/.*/,namespace:'isolated'},()=>({contents:'export function randomInt(max){if(!Number.isInteger(max)||max<1)throw Error("Invalid bound");const a=new Uint32Array(1),limit=4294967296-(4294967296%max);do{crypto.getRandomValues(a);}while(a[0]>=limit);return a[0]%max;}',loader:'js'}));}};
const bundle=async(file,plugins=[])=>(await build({entryPoints:[file],bundle:true,write:false,format:'iife',target:'chrome58',minify:true,plugins})).outputFiles[0].text;
const engine=await bundle('src/adapter.js',[randomPlugin]),client=await bundle('src/view.js');const css=(await Promise.all(['style.css','games.css','werewolf.css'].map(p=>readFile('public/'+p,'utf8')))).join('\n');
const assets={};async function scan(dir,path=''){for(const item of await readdir(dir,{withFileTypes:true})){const key=path+item.name;if(item.isDirectory())await scan(dir+'/'+item.name,key+'/');else if(/\.(png|jpg|mp3)$/.test(key))assets[key]={type:key.endsWith('.mp3')?'audio/mpeg':key.endsWith('.png')?'image/png':'image/jpeg',data:(await readFile(dir+'/'+item.name)).toString('base64')};}}
try{await scan('assets');}catch(e){if(e.code!=='ENOENT')throw e;}
const compat=await readFile('public/compat.js','utf8');
const view='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+css+'\n.game-pairing,.wolf-qr{display:none!important}.game-stage{min-height:0}.game-shell{height:100vh!important;min-height:0!important}.game-shell .game-stage{flex:1}.sound-controls{position:fixed;z-index:100;right:8px;top:8px;display:flex;gap:5px}.sound-controls button{padding:8px;font-size:12px}[data-fullscreen]{visibility:hidden}.game-footer{padding-right:160px}</style></head><body><main id="app"></main><div class="sound-controls"><button id="sound" class="button">♪</button><button id="music" class="button">♫</button></div><div id="notice" role="status"></div><script>'+compat.replaceAll('</script','<\\/script')+'</script><script>'+client.replaceAll('</script','<\\/script')+'</script></body></html>';
await mkdir('dist',{recursive:true});await writeFile('dist/game.rmg.json',JSON.stringify({manifest,engine,view,assets,licenseText:await readFile('LICENSE','utf8')}));console.log('Built '+manifest.id+' '+manifest.version);
